spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQL
#      database-platform: org.hibernate.dialect.MySQL
#    properties:
#      hibernate:
#        format_sql: true
#    show-sql: true
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/examplesp?useSSL=false
    driverClassName: com.mysql.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: quanglinh821997@gmail.com
    password: ynhgyescitlgehsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#      springframework: DEBUG
