spring:
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
    show-sql: true
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/examplesp?useSSL=false
  mail:
    host: smtp.gmail.com
    port: 587
    username: quanglinh821997@gmail.com
    password: ynhgyescitlgehsy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        jdbc:
          core:
            JdbcTemplate: DEBUG